modLoader = "javafml"
loaderVersion = "[33,)"
license = "BSD-3-Clause License for Code"
# issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]]
modId = "contact"
version = "${file.jarVersion}"
displayName = "Contact"
# updateJSONURL="http://myurl.me/"
# displayURL="http://example.com/"
logoFile = "logo.png"
credits = "Lemon Slice Studio"
authors = "RoitoLeo, Gloridifice, MalayP"
description = '''This is a mod that provides postal service.'''
[[dependencies.contact]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.contact]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
[[dependencies.contact]]
modId = "silveroakoutpost"
mandatory = true
versionRange = "[0.4.5-Alpha,)"
ordering = "NONE"
side = "BOTH"
